### PR TITLE
release(v1.2.2): updating version to v1.2.2-beta-1

### PR DESCRIPTION
**Pull request by jaellio**
Updates versions and image tags in chart.yaml and values.yaml

- [x] I have ensured that required images are available in MCR:
	1. osm-controller, osm-injector, osm-bootstrap, osm-crds and init images of the corresponding chart version
	2. envoy image of version listed in osm-arc/oss values.yaml
    3. grafana, grafana-image-renderer, prometheus, jaegertracing/all-in-one image of version listed in osm-arc/oss values.yaml
- [x] I have ensured that all the images mentioned in the previous step (aside from grafana-image-renderer) are available for both amd64 and arm64 architectures
- [x] I have updated the Helm chart:
    1. Updated the chart version, app version and dependency version in charts/osm-arc/Chart.yaml    
    2. Made applicable updates to the osm-arc values.yaml if any were made in the upstream OSM chart
    
       
- [x] I have received 3 approvals from maintainers.

### CODE REVIEW

**Comment by jaellio** [comment]
@microsoft-github-policy-service agree Microsoft

**Comment by jaellio** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by keithmattix — APPROVED** [review]

**Review by SanyaKochhar — APPROVED** [review]

**Review by nshankar13 — APPROVED** [review]

**Pull request merged**
