### PR TITLE
release(v1.2.3): update v1.2.3-beta-1 to v1.2.3

### PR DESCRIPTION
**Pull request by jaellio**
**Description**:

Updates v1.2.3-beta-1 to v1.2.3.

**Release PR checklist**:

- [x] I have ensured that required images are available in MCR:
	1. osm-controller, osm-injector, osm-bootstrap, osm-crds and init images of the corresponding chart version
	2. envoy image of version listed in osm-arc/oss values.yaml
    3. grafana, grafana-image-renderer, prometheus, jaegertracing/all-in-one image of version listed in osm-arc/oss values.yaml
- [x] I have ensured that all the images mentioned in the previous step (aside from grafana-image-renderer) are available for both amd64 and arm64 architectures
- [x] I have updated the Helm chart:
    1. Updated the chart version, app version and dependency version in charts/osm-arc/Chart.yaml    
    2. Made applicable updates to the osm-arc values.yaml if any were made in the upstream OSM chart
    
       
- [x] I have received 3 approvals from maintainers.

### CODE REVIEW

**Review by nshankar13 — APPROVED** [review]

**Review by SanyaKochhar — APPROVED** [review]

**Review by keithmattix — APPROVED** [review]

**Comment by jaellio** [comment]
`upgrade-e2e-arc` currently failing on the add arc extension step with the following error https://dev.azure.com/AzureContainerUpstream/OpenServiceMesh/_build/results?buildId=77823&view=logs&j=9de9e2b7-8af7-5276-a88f-b4157127a375&t=7b562f13-6eeb-5d13-f93d-83775efe83f4&l=17

**Pull request merged**
