### PR TITLE
Update version v1.1.1

### PR DESCRIPTION
**Pull request by nshankar13**
Signed-off-by: nshankar13 <nshankar@microsoft.com>

- [x] I have ensured that required images are available in MCR:
	1. osm-controller, osm-injector, osm-bootstrap, osm-crds and init images of the corresponding chart version
	2. envoy image of version listed in osm-arc/oss values.yaml
    3. grafana, grafana-image-renderer, prometheus, jaegertracing/all-in-one image of version listed in osm-arc/oss values.yaml
- [x] I have ensured that all the images mentioned in the previous step (aside from grafana-image-renderer) are available for both amd64 and arm64 architectures
- [x] I have updated the Helm chart:
    1. Updated the chart version, app version and dependency version in charts/osm-arc/Chart.yaml    
    2. Made applicable updates to the osm-arc values.yaml if any were made in the upstream OSM chart
    
       
- [x] I have received 3 approvals from maintainers. 

**Description**: Update version to 1.1.1. Deleting validatge-single-mesh pre-install job as OSM upstream now does enforce-single-mesh validation via helm instead of OSM cli. https://github.com/Azure/osm-azure/issues/144. Validated that installation is blocked on a cluster that already has OSM installed. 

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Networking             [ ]
- Metrics                [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

### CODE REVIEW

**Review by trstringer — APPROVED** [review]

**Review by SanyaKochhar — APPROVED** [review]
Is Prometheus version 2.18.1 now available in MCR? also jw why is validate single mesh being removed?

**Comment by nshankar13** [comment]
@SanyaKochhar v2.18.1 cannot be pushed to MCR due to backwards incompatibility with prometheus build pipeline, but the plan is to use a more updated prometheus version v2.34.0. Currently testing that this works. 

Explanation for validate single mesh is in PR description: 

> Update version to 1.1.0 Deleting validatge-single-mesh pre-install job as OSM upstream now does enforce-single-mesh validation via helm instead of OSM cli. https://github.com/Azure/osm-azure/issues/144. Validated that installation is blocked on a cluster that already has OSM installed.

**Comment by SanyaKochhar** [comment]
@nshankar13 oop thanks, totally missed that
> Explanation for validate single mesh is in PR description:

**Review by chewong — APPROVED** [review]

**Pull request merged**
