### PR TITLE
ref(chart): Keeps debug server disabled by default

### LINKED ISSUE #46: enableDebugServer is enabled by default
enableDebugServer should be false for the osm-azure chart so that the endpoint isn't exposed unnecessarily.

If debugging is needed, it can be turned on in the osm config map.

### PR DESCRIPTION
**Pull request by ksubrmnn**
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>

Fixes #46

### CODE REVIEW

**Review by nshankar13 — APPROVED** [review]

**Review by michelleN — COMMENTED** [review]
Should we leave this exposed but default it to false in case folks want to use it? _or_ is it the case that this just should never be an option in which case deleting makes sense as well.

**Comment by ritazh** [comment]
> Should we leave this exposed but default it to false in case folks want to use it? or is it the case that this just should never be an option in which case deleting makes sense as well.

Removing this field from osm-arc values.yaml will make it inherit the default `false` from the dependent oss chart. If we want to be more opinionated and make sure this is always default to false in osm-arc, then let's set it explicitly to `false`.

**Review by ritazh — APPROVED** [review]

**Review by nshankar13 — APPROVED** [review]

**Pull request merged**
