### PR TITLE
Bump osm-azure to latest version

### PR DESCRIPTION
**Pull request by keithmattix**
- [X] I have ensured that required images are available in MCR:
	1. osm-controller, osm-injector, osm-bootstrap, osm-crds and init images of the corresponding chart version
	2. envoy image of version listed in osm-arc/oss values.yaml
    3. grafana, grafana-image-renderer, prometheus, jaegertracing/all-in-one image of version listed in osm-arc/oss values.yaml
- [X] I have ensured that all the images mentioned in the previous step (aside from grafana-image-renderer) are available for both amd64 and arm64 architectures
- [X] I have updated the Helm chart:
    1. Updated the chart version, app version and dependency version in charts/osm-arc/Chart.yaml    
    2. Made applicable updates to the osm-arc values.yaml if any were made in the upstream OSM chart
    
       
- [ ] I have received 3 approvals from maintainers.

### CODE REVIEW

**Review by nshankar13 — APPROVED** [review]

**Comment by nshankar13** [comment]
@keithmattix here is the release template for Arc releases for PR descriptions: https://raw.githubusercontent.com/Azure/osm-azure/main/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md.

Going forward, I think we can reduce this to two approvals instead of 3.

**Review by jaellio — APPROVED** [review]

**Pull request merged**
