### PR TITLE
Separate enable-arc and osm-installation

### PR DESCRIPTION
**Pull request by nshankar13**
Split the add-extension script into two: one to enable arc on the cluster, and another to install the osm extension. 

NOTE: Once this PR is merged, the ADO pipeline will also need to be changed to call the connect-to-arc script before installing the osm-extension.

### CODE REVIEW

**Review by ksubrmnn — DISMISSED** [review]
I like this change. @ritazh Should we also just get rid of update-extension.sh script since it now does pretty much the same thing as this new add-extension.sh?

**Review by SanyaKochhar — APPROVED** [review]

**Review by ksubrmnn — APPROVED** [review]

**Comment by ritazh** [comment]
> I like this change. @ritazh Should we also just get rid of update-extension.sh script since it now does pretty much the same thing as this new add-extension.sh?

Let's leave it as in the future it should be using `az extension update` for that script.

**Review by ritazh — APPROVED** [review]

**Pull request merged**
